main: me.mrmacor.teleporters.Teleporters
name: Teleporters
version: 2.0
description: Teleporters is a light-weight plugin that lets players create and link teleporter pads easily.
api-version: 1.15
author: MrMacor
commands:
  linkpads:
        description: Command used to link teleport pads
